#! /usr/bin/env python
# -*- coding: utf-8 -*-
import argparse
import numpy
from matplotlib import pyplot as plt
import voropy


def _parse_input_arguments():
    parser = argparse.ArgumentParser(
        description='Perform Lloyd smoothing on a 2D mesh.'
        )

    parser.add_argument(
        'input',
        metavar='INPUT',
        type=str,
        help='Input file'
        )

    parser.add_argument(
        'output',
        metavar='OUTPUT',
        type=str,
        help='Output file'
        )

    parser.add_argument(
        '--tolerance', '-t',
        metavar='TOL',
        type=float,
        required=True,
        help='convergence criterium (maximum move)'
        )

    parser.add_argument(
        '--verbose', '-v',
        dest='verbose',
        action='store_true',
        default=False
        )

    parser.add_argument(
        '--output-step-filetype', '-s',
        dest='output_steps',
        default=None,
        help='write mesh after each Lloyd step'
        )

    return parser.parse_args()


if __name__ == '__main__':
    args = _parse_input_arguments()
    mesh, _, _, _ = voropy.read(args.input, flat_boundary_correction=True)
    out_mesh = voropy.mesh_tri.lloyd_smoothing(
        mesh,
        args.tolerance,
        verbose=args.verbose,
        output_filetype=args.output_steps
        )
    out_mesh.write(args.output)
