#! /usr/bin/env python
# -*- coding: utf-8 -*-
import argparse
import numpy
from matplotlib import pyplot as plt
import meshio
import voropy


def _parse_input_arguments():
    parser = argparse.ArgumentParser(
        description='Show triangular mesh with control volumes etc.'
        )

    parser.add_argument(
        'file',
        metavar='FILE',
        type=str,
        help='Input file'
        )

    return parser.parse_args()


if __name__ == '__main__':
    args = _parse_input_arguments()

    pts, cells, _, _, _ = meshio.read(args.file)
    cells = cells['triangle']

    # toss away all nodes which don't belong to cells
    uvertices, uidx = numpy.unique(cells, return_inverse=True)
    cells = uidx.reshape(cells.shape)
    pts = pts[uvertices]

    mesh = voropy.mesh_tri.MeshTri(pts, cells)

    mesh.show()
    plt.show()
